### PR TITLE
Repl.it and gitignore changes

### PR DESCRIPTION
**Pull request by Kore-Development**
Added gitignore entries from Node.js template, added .env file, improved Repl.it support

I made some changes to the code for HTTPS because Repl.it manages SSL for you. Because Repl.it doesn't support changing environment variables without a .env file I have added support for .env files. By the way, if .env ever contains information that needs to be kept hidden Repl.it hides the .env file from other users. I also added some entries from the Node.js gitignore template located [here](https://github.com/github/gitignore/blob/master/Node.gitignore).

### CODE REVIEW

**Comment by OhMyGuus** [comment]
I'm a fan of the .env file so thanks for implementing that, but I see you also added replit specific code and I don't know if I see a reason for that tbh. Since replit sets a port to the process.env.PORT already (correct me if I'm not wrong) so it doesn't need those lines to startup. 

So I properly won't merge those changes, but if those changes where to fix the https on the website, then the fix is to add 
`
app.enable('trust proxy');
`
Since that will allow reverse proxies I will add that when I merge this.

**Comment by Kore-Development** [comment]
Repl.it sets up SSL for you so the HTTPS code is not necessary for Repl.it. It might actually set the port so that part could possibly be reverted.

**Comment by Kore-Development** [comment]
I just checked, and it does not set the PORT variable. It also does not have permission to use some ports but 9736 is available.

**Comment by OhMyGuus** [comment]
> I just checked, and it does not set the PORT variable. It also does not have permission to use some ports but 9736 is available.



> I just checked, and it does not set the PORT variable. It also does not have permission to use some ports but 9736 is available.


Oh nvm sorry for the late response but it looks like that the port doesn't matter for replit, it will just forward the first tcp port that is listening.

**Pull request closed without merging**
